#!/usr/bin/env zsh

# WSL 1 or 2
if [[ $OSTYPE == linux* && -r /proc/version &&
    $(< /proc/version) == *[Mm]icrosoft* ]]; then
  clip.exe
elif (( $+commands[xclip] )); then
  xclip -selection clipboard -in
elif (( $+commands[xsel] )); then
  xsel -b
elif [[ "$OSTYPE" == darwin* ]]; then
  command pbcopy
elif [[ "$OSTYPE" == (cygwin*|msys) ]]; then
  tee > /dev/clipboard
fi
