#!/usr/bin/env zsh

# WSL 1 or 2
if [[ $OSTYPE == linux* && -r /proc/version &&
    $(< /proc/version) == *[Mm]icrosoft* ]]; then
  powershell.exe -Command Get-Clipboard
elif (( $+commands[xclip] )); then
  xclip -selection clipboard -out
elif (( $+commands[xsel] )); then
  xsel -b
elif [[ "$OSTYPE" == darwin* ]]; then
  command pbpaste
elif [[ "$OSTYPE" == (cygwin*|msys) ]]; then
  cat /dev/clipboard
fi
